architecture: conv
training_parameters:
  batch_size: 100
  batch_buffer_size: 1000
  scale_features: norm
  shuffle: true
  train_size: 0.8
validation_parameters:
  batch_size: 1000
  batch_buffer_size: 10
  scale_features: norm
  shuffle: true
weight_expression: weight_total*xs/sumw
features:
- JetImageFine_FloatE
arch_parameters:
  n_layers_for_conv: 2
  n_filters_for_conv: [32,32]
  filter_size_for_conv: [3,3]
  pool_size_for_conv: [2,2]
  n_layers_for_dense: 3
  n_nodes_for_dense: [200,200,200]
  image_shape: [59, 45, 1]
  dropout: 0
