architecture: dense
training_parameters:
  batch_size: 25
  batch_buffer_size: 500000
  train_size: 0.7
  scale_features: standard
  shuffle: true
validation_parameters:
  batch_size: 10000
  batch_buffer_size: 100
  scale_features: standard
  shuffle: true
weight_expression: weight_total*xs/sumw
features:
- mjj
- dphijj
- detajj

arch_parameters:
  n_features: 3
  n_classes: 2
  n_nodes: [18,10,5,2]
  dropout: 0.2
