
name: tests
# Running tests on all branches
on: [pull_request]

jobs:
  # This is a job for linux python3 tests
  linuxpy3:
      runs-on: [ubuntu-20.04]
      steps:
        - uses: actions/checkout@v2

        # Install dependencies
        - name: Install python dependencies
          run: |
            curl https://bootstrap.pypa.io/get-pip.py > get-pip.py
            python3 get-pip.py

        # Install vbfml package
        # We'll install tensorflow and scikit-learn separately
        # since we don't have them in requirements.txt
        - name: Install this package
          run: |
            python3 -m pip install -e .
            python3 -m pip install tensorflow==2.5.0
            python3 -m pip install scikit-learn==0.24.2

        # Run black code formatter
        - name: black
          run: |
            black --check vbfml

        # Run unit tests via pytest
        - name: pytest
          run: |
            python3 -m pytest